version: '3.8'

# Versão LITE para máquinas com poucos recursos
# Windows 10 + 4GB RAM + Celeron

services:
  # PostgreSQL com configurações mínimas
  postgres:
    image: postgres:15-alpine
    container_name: pizzaria-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pizzaria_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-8477}
      # Configurações para usar menos memória
      POSTGRES_SHARED_BUFFERS: 128MB
      POSTGRES_WORK_MEM: 2MB
      POSTGRES_MAINTENANCE_WORK_MEM: 32MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 256MB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/scripts/create-database-complete.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "5432:5432"
    networks:
      - pizzaria-network
    # Limitar recursos
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    command: >
      postgres
      -c shared_buffers=128MB
      -c work_mem=2MB
      -c maintenance_work_mem=32MB
      -c effective_cache_size=256MB
      -c max_connections=50

  # Backend Node.js otimizado
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pizzaria-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: pizzaria_db
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD:-8477}
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_here}
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost
      # Limitar memória do Node.js
      NODE_OPTIONS: "--max-old-space-size=384"
    depends_on:
      - postgres
    networks:
      - pizzaria-network
    ports:
      - "3001:3001"
    # Limitar recursos
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Frontend servido pelo Node.js (sem Nginx para economizar RAM)
  frontend-lite:
    image: node:18-alpine
    container_name: pizzaria-frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_OPTIONS: "--max-old-space-size=256"
    command: >
      sh -c "
        npm install &&
        npm run build &&
        npx serve -s dist -l 80
      "
    ports:
      - "80:80"
    networks:
      - pizzaria-network
    depends_on:
      - backend
    # Limitar recursos
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  pizzaria-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local